export const defaultUrl = `https://api.mercadolibre.com`;

export const TYPES = {
  SET_LOADING: "SET_LOADING",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_TECH: "GET_PRODUCTS_TECH",
  GET_PRODUCTS_SPORT: "GET_PRODUCTS_SPORT",
  GET_PRODUCTS_VEHICLES: "GET_PRODUCTS_VEHICLES",
  GET_PRODUCTS_ESTATE: "GET_PRODUCTS_ESTATE",
  GET_PRODUCTS_APPLIANCE: "GET_PRODUCTS_APPLIANCE",
  GET_PRODUCTS_CONSTRUCTION: "GET_PRODUCTS_CONSTRUCTION",
  GET_PRODUCTS_SCIENCE: "GET_PRODUCTS_SCIENCE",
  GET_PRODUCTS_BEAUTY: "GET_PRODUCTS_BEAUTY",
  GET_PRODUCTS_STYLE: "GET_PRODUCTS_STYLE",
  GET_PRODUCTS_HEALTH: "GET_PRODUCTS_HEALTH",
  GET_PRODUCT_ID: "GET_PRODUCT_ID",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
};
